name: Build & Release

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build & Release
        uses: ./.github/actions/latexmk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
